from typing import Protocol


class GitService(Protocol):
    async def clone_repository(self, url, base_ref, token): ...
    async def fetch(self, token): ...
    async def status(self): ...
    async def current_branch(self): ...
    async def list_branches(self): ...
    async def create_branch(self, branch): ...
    async def checkout(self, branch): ...
    async def diff(self): ...
    async def log(self): ...
    async def stage_paths(self, paths): ...
    async def commit(self, message): ...
    async def push_branch(self, branch, token): ...
    async def restore_paths(self, paths): ...
    async def get_changed_files(self): ...
    async def get_remote_info(self): ...
