from typing import Protocol


class WorkspaceStorage(Protocol):
    def create_workspace(self, user_id: int, workspace_id: str): ...
    def save_upload(self, user_id: int, workspace_id: str, filename: str, data: bytes): ...
    def extract_archive(self, user_id: int, workspace_id: str, filename: str, data: bytes): ...
    def list_files(self, user_id: int, workspace_id: str): ...
    def read_file(self, user_id: int, workspace_id: str, path: str): ...
    def write_file(self, user_id: int, workspace_id: str, path: str, data: bytes): ...
    def delete_workspace(self, user_id: int, workspace_id: str): ...
