"""stage 5 and 6 github mcp oauth integration jobs"""

import sqlalchemy as sa

from alembic import op

revision = "45e2729dffcb"
down_revision = "70b1efb2e547"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "github_connections",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("connection_type", sa.String(length=20), nullable=False),
        sa.Column("github_user_id", sa.BigInteger(), nullable=True),
        sa.Column("github_login", sa.String(length=100), nullable=True),
        sa.Column("installation_id", sa.BigInteger(), nullable=True),
        sa.Column("encrypted_token", sa.Text(), nullable=True),
        sa.Column("token_hint", sa.String(length=30), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.Column("last_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_github_connections_user_id"), "github_connections", ["user_id"], unique=False
    )
    op.create_table(
        "integration_oauth_states",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("target_id", sa.String(length=36), nullable=False),
        sa.Column("nonce_hash", sa.String(length=64), nullable=False),
        sa.Column("payload_encrypted", sa.Text(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_integration_oauth_states_user_id"),
        "integration_oauth_states",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "mcp_servers",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("transport", sa.String(length=30), nullable=False),
        sa.Column("server_url", sa.String(length=2048), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("auth_type", sa.String(length=20), nullable=False),
        sa.Column("encrypted_auth_config", sa.Text(), nullable=True),
        sa.Column("protocol_version", sa.String(length=30), nullable=True),
        sa.Column("server_info_json", sa.JSON(), nullable=False),
        sa.Column("capabilities_json", sa.JSON(), nullable=False),
        sa.Column("last_connected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_discovered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_mcp_servers_user_id"), "mcp_servers", ["user_id"], unique=False)
    op.create_table(
        "github_repositories",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("github_connection_id", sa.String(length=36), nullable=False),
        sa.Column("github_repository_id", sa.BigInteger(), nullable=False),
        sa.Column("owner", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("full_name", sa.String(length=210), nullable=False),
        sa.Column("default_branch", sa.String(length=255), nullable=False),
        sa.Column("visibility", sa.String(length=20), nullable=False),
        sa.Column("web_url", sa.String(length=512), nullable=False),
        sa.Column("clone_url", sa.String(length=512), nullable=False),
        sa.Column("is_archived", sa.Boolean(), nullable=False),
        sa.Column("is_disabled", sa.Boolean(), nullable=False),
        sa.Column("permissions_json", sa.JSON(), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["github_connection_id"], ["github_connections.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("github_connection_id", "github_repository_id"),
    )
    op.create_index(
        op.f("ix_github_repositories_github_connection_id"),
        "github_repositories",
        ["github_connection_id"],
        unique=False,
    )
    op.create_table(
        "mcp_credentials",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("mcp_server_id", sa.String(length=36), nullable=False),
        sa.Column("credential_type", sa.String(length=30), nullable=False),
        sa.Column("encrypted_access_token", sa.Text(), nullable=False),
        sa.Column("encrypted_refresh_token", sa.Text(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("scopes_json", sa.JSON(), nullable=False),
        sa.Column("issuer", sa.String(length=2048), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["mcp_server_id"], ["mcp_servers.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("mcp_server_id"),
    )
    op.create_index(
        op.f("ix_mcp_credentials_user_id"), "mcp_credentials", ["user_id"], unique=False
    )
    op.create_table(
        "mcp_resources",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("mcp_server_id", sa.String(length=36), nullable=False),
        sa.Column("uri", sa.String(length=2048), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("mime_type", sa.String(length=100), nullable=True),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["mcp_server_id"], ["mcp_servers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("mcp_server_id", "uri"),
    )
    op.create_index(
        op.f("ix_mcp_resources_mcp_server_id"), "mcp_resources", ["mcp_server_id"], unique=False
    )
    op.create_table(
        "mcp_tools",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("mcp_server_id", sa.String(length=36), nullable=False),
        sa.Column("external_name", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("input_schema_json", sa.JSON(), nullable=False),
        sa.Column("output_schema_json", sa.JSON(), nullable=True),
        sa.Column("risk_level", sa.String(length=20), nullable=False),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column("requires_approval", sa.Boolean(), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["mcp_server_id"], ["mcp_servers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("mcp_server_id", "external_name"),
    )
    op.create_index(
        op.f("ix_mcp_tools_mcp_server_id"), "mcp_tools", ["mcp_server_id"], unique=False
    )
    op.create_table(
        "repository_workspaces",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.Column("github_repository_id", sa.String(length=36), nullable=False),
        sa.Column("connection_id", sa.String(length=36), nullable=False),
        sa.Column("remote_name", sa.String(length=30), nullable=False),
        sa.Column("default_branch", sa.String(length=255), nullable=False),
        sa.Column("base_ref", sa.String(length=255), nullable=False),
        sa.Column("working_branch", sa.String(length=255), nullable=True),
        sa.Column("base_commit_sha", sa.String(length=64), nullable=False),
        sa.Column("last_fetched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["connection_id"], ["github_connections.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["github_repository_id"], ["github_repositories.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workspace_id"),
    )
    op.create_index(
        op.f("ix_repository_workspaces_user_id"), "repository_workspaces", ["user_id"], unique=False
    )
    op.add_column(
        "agent_jobs",
        sa.Column("kind", sa.String(length=50), server_default="AGENT", nullable=False),
    )
    op.add_column("agent_jobs", sa.Column("payload_encrypted", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("agent_jobs", "payload_encrypted")
    op.drop_column("agent_jobs", "kind")
    op.drop_index(op.f("ix_repository_workspaces_user_id"), table_name="repository_workspaces")
    op.drop_table("repository_workspaces")
    op.drop_index(op.f("ix_mcp_tools_mcp_server_id"), table_name="mcp_tools")
    op.drop_table("mcp_tools")
    op.drop_index(op.f("ix_mcp_resources_mcp_server_id"), table_name="mcp_resources")
    op.drop_table("mcp_resources")
    op.drop_index(op.f("ix_mcp_credentials_user_id"), table_name="mcp_credentials")
    op.drop_table("mcp_credentials")
    op.drop_index(
        op.f("ix_github_repositories_github_connection_id"), table_name="github_repositories"
    )
    op.drop_table("github_repositories")
    op.drop_index(op.f("ix_mcp_servers_user_id"), table_name="mcp_servers")
    op.drop_table("mcp_servers")
    op.drop_index(
        op.f("ix_integration_oauth_states_user_id"), table_name="integration_oauth_states"
    )
    op.drop_table("integration_oauth_states")
    op.drop_index(op.f("ix_github_connections_user_id"), table_name="github_connections")
    op.drop_table("github_connections")
    # ### end Alembic commands ###
