"""stage 4 secure agent jobs approvals snapshots validation"""

import sqlalchemy as sa

from alembic import op

revision = "70b1efb2e547"
down_revision = "f5b9bb2e57e2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_jobs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("mode", sa.String(length=20), nullable=False),
        sa.Column("request_text", sa.Text(), nullable=False),
        sa.Column("plan_json", sa.JSON(), nullable=False),
        sa.Column("plan_encrypted", sa.Text(), nullable=True),
        sa.Column("current_step", sa.Integer(), nullable=False),
        sa.Column("max_steps", sa.Integer(), nullable=False),
        sa.Column("tool_calls_count", sa.Integer(), nullable=False),
        sa.Column("model_requests", sa.Integer(), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("replan_count", sa.Integer(), nullable=False),
        sa.Column("repair_count", sa.Integer(), nullable=False),
        sa.Column("validation_runtime_ms", sa.Integer(), nullable=False),
        sa.Column("elapsed_ms", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failure_code", sa.String(length=50), nullable=True),
        sa.Column("failure_message_safe", sa.String(length=100), nullable=True),
        sa.Column("result_json", sa.JSON(), nullable=False),
        sa.Column("telegram_chat_id", sa.BigInteger(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_agent_jobs_status"), "agent_jobs", ["status"], unique=False)
    op.create_index(op.f("ix_agent_jobs_user_id"), "agent_jobs", ["user_id"], unique=False)
    op.create_index(
        op.f("ix_agent_jobs_workspace_id"), "agent_jobs", ["workspace_id"], unique=False
    )
    op.create_table(
        "agent_steps",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.String(length=36), nullable=False),
        sa.Column("step_number", sa.Integer(), nullable=False),
        sa.Column("step_type", sa.String(length=30), nullable=False),
        sa.Column("tool_name", sa.String(length=80), nullable=True),
        sa.Column("input_json_redacted", sa.JSON(), nullable=False),
        sa.Column("output_summary", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["job_id"], ["agent_jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("job_id", "step_number"),
    )
    op.create_index(op.f("ix_agent_steps_job_id"), "agent_steps", ["job_id"], unique=False)
    op.create_table(
        "approvals",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("job_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("action_type", sa.String(length=30), nullable=False),
        sa.Column("tool_name", sa.String(length=80), nullable=False),
        sa.Column("arguments_summary", sa.JSON(), nullable=False),
        sa.Column("arguments_hash", sa.String(length=64), nullable=False),
        sa.Column("risk_level", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("step_number", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["job_id"], ["agent_jobs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_approvals_job_id"), "approvals", ["job_id"], unique=False)
    op.create_index(op.f("ix_approvals_user_id"), "approvals", ["user_id"], unique=False)
    op.create_table(
        "tool_calls",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.String(length=36), nullable=False),
        sa.Column("tool_name", sa.String(length=80), nullable=False),
        sa.Column("risk_level", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("input_summary", sa.JSON(), nullable=False),
        sa.Column("output_summary", sa.JSON(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["job_id"], ["agent_jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tool_calls_job_id"), "tool_calls", ["job_id"], unique=False)
    op.create_table(
        "validation_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("job_id", sa.String(length=36), nullable=False),
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.Column("command_id", sa.String(length=50), nullable=False),
        sa.Column("command_json", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("exit_code", sa.Integer(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("output_encrypted", sa.Text(), nullable=True),
        sa.Column("output_truncated", sa.Boolean(), nullable=False),
        sa.Column("findings_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["job_id"], ["agent_jobs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_validation_runs_job_id"), "validation_runs", ["job_id"], unique=False)
    op.create_index(
        op.f("ix_validation_runs_workspace_id"), "validation_runs", ["workspace_id"], unique=False
    )
    op.create_table(
        "workspace_change_sets",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.Column("job_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("proposal_encrypted", sa.Text(), nullable=False),
        sa.Column("diff_encrypted", sa.Text(), nullable=False),
        sa.Column("summary_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["job_id"], ["agent_jobs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_workspace_change_sets_job_id"), "workspace_change_sets", ["job_id"], unique=False
    )
    op.create_index(
        op.f("ix_workspace_change_sets_workspace_id"),
        "workspace_change_sets",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "file_snapshots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("change_set_id", sa.String(length=36), nullable=False),
        sa.Column("relative_path", sa.String(length=2048), nullable=False),
        sa.Column("original_sha256", sa.String(length=64), nullable=True),
        sa.Column("resulting_sha256", sa.String(length=64), nullable=True),
        sa.Column("content_encrypted", sa.Text(), nullable=True),
        sa.Column("existed", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["change_set_id"], ["workspace_change_sets.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("change_set_id", "relative_path"),
    )
    op.create_index(
        op.f("ix_file_snapshots_change_set_id"), "file_snapshots", ["change_set_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_file_snapshots_change_set_id"), table_name="file_snapshots")
    op.drop_table("file_snapshots")
    op.drop_index(op.f("ix_workspace_change_sets_workspace_id"), table_name="workspace_change_sets")
    op.drop_index(op.f("ix_workspace_change_sets_job_id"), table_name="workspace_change_sets")
    op.drop_table("workspace_change_sets")
    op.drop_index(op.f("ix_validation_runs_workspace_id"), table_name="validation_runs")
    op.drop_index(op.f("ix_validation_runs_job_id"), table_name="validation_runs")
    op.drop_table("validation_runs")
    op.drop_index(op.f("ix_tool_calls_job_id"), table_name="tool_calls")
    op.drop_table("tool_calls")
    op.drop_index(op.f("ix_approvals_user_id"), table_name="approvals")
    op.drop_index(op.f("ix_approvals_job_id"), table_name="approvals")
    op.drop_table("approvals")
    op.drop_index(op.f("ix_agent_steps_job_id"), table_name="agent_steps")
    op.drop_table("agent_steps")
    op.drop_index(op.f("ix_agent_jobs_workspace_id"), table_name="agent_jobs")
    op.drop_index(op.f("ix_agent_jobs_user_id"), table_name="agent_jobs")
    op.drop_index(op.f("ix_agent_jobs_status"), table_name="agent_jobs")
    op.drop_table("agent_jobs")
    # ### end Alembic commands ###
