"""distinguish price estimates from actual provider billing"""

import sqlalchemy as sa

from alembic import op

revision = "771dc45faaa3"
down_revision = "a4bcb8ee6bcb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "usage_entries",
        sa.Column("pricing_status", sa.String(length=20), server_default="UNKNOWN", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("usage_entries", "pricing_status")
    # ### end Alembic commands ###
