"""stage 7 8 memory graph usage quotas flags admin"""

import sqlalchemy as sa

from alembic import op

revision = "8c248b07f28e"
down_revision = "45e2729dffcb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admin_audit",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("subject", sa.String(length=255), nullable=False),
        sa.Column("action", sa.String(length=80), nullable=False),
        sa.Column("target", sa.String(length=100), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_admin_audit_action"), "admin_audit", ["action"], unique=False)
    op.create_index(op.f("ix_admin_audit_created_at"), "admin_audit", ["created_at"], unique=False)
    op.create_index(op.f("ix_admin_audit_subject"), "admin_audit", ["subject"], unique=False)
    op.create_table(
        "admin_identities",
        sa.Column("subject", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=30), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("subject"),
    )
    op.create_table(
        "feature_flags",
        sa.Column("key", sa.String(length=80), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("targets_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "plan_policies",
        sa.Column("name", sa.String(length=30), nullable=False),
        sa.Column("limits_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "user_plans",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("plan", sa.String(length=30), nullable=False),
        sa.Column("overrides_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "agent_graph_nodes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.String(length=36), nullable=False),
        sa.Column("node_key", sa.String(length=80), nullable=False),
        sa.Column("role", sa.String(length=40), nullable=False),
        sa.Column("dependencies", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("result_encrypted", sa.Text(), nullable=True),
        sa.Column("model_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["job_id"], ["agent_jobs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["model_id"], ["models.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("job_id", "node_key"),
    )
    op.create_index(
        op.f("ix_agent_graph_nodes_job_id"), "agent_graph_nodes", ["job_id"], unique=False
    )
    op.create_table(
        "memory_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("workspace_id", sa.String(length=36), nullable=True),
        sa.Column("job_id", sa.String(length=36), nullable=True),
        sa.Column("layer", sa.String(length=30), nullable=False),
        sa.Column("scope_key", sa.String(length=100), nullable=False),
        sa.Column("digest", sa.String(length=64), nullable=False),
        sa.Column("content_encrypted", sa.Text(), nullable=False),
        sa.Column("search_terms", sa.JSON(), nullable=False),
        sa.Column("provenance_json", sa.JSON(), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=4, scale=3), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["job_id"], ["agent_jobs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "scope_key", "digest"),
    )
    op.create_index(op.f("ix_memory_items_job_id"), "memory_items", ["job_id"], unique=False)
    op.create_index(op.f("ix_memory_items_user_id"), "memory_items", ["user_id"], unique=False)
    op.create_index(
        op.f("ix_memory_items_workspace_id"), "memory_items", ["workspace_id"], unique=False
    )
    op.create_table(
        "usage_entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=200), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("provider_id", sa.Integer(), nullable=True),
        sa.Column("model_id", sa.Integer(), nullable=True),
        sa.Column("job_id", sa.String(length=36), nullable=True),
        sa.Column("operation", sa.String(length=40), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("estimated_cost", sa.Numeric(precision=18, scale=8), nullable=True),
        sa.Column("actual_cost", sa.Numeric(precision=18, scale=8), nullable=True),
        sa.Column("tool_calls", sa.Integer(), nullable=False),
        sa.Column("storage_bytes", sa.Integer(), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["job_id"], ["agent_jobs.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["model_id"], ["models.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["provider_id"], ["providers.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key"),
    )
    op.create_index(
        op.f("ix_usage_entries_created_at"), "usage_entries", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_usage_entries_job_id"), "usage_entries", ["job_id"], unique=False)
    op.create_index(
        op.f("ix_usage_entries_operation"), "usage_entries", ["operation"], unique=False
    )
    op.create_index(
        op.f("ix_usage_entries_provider_id"), "usage_entries", ["provider_id"], unique=False
    )
    op.create_index(op.f("ix_usage_entries_user_id"), "usage_entries", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_usage_entries_user_id"), table_name="usage_entries")
    op.drop_index(op.f("ix_usage_entries_provider_id"), table_name="usage_entries")
    op.drop_index(op.f("ix_usage_entries_operation"), table_name="usage_entries")
    op.drop_index(op.f("ix_usage_entries_job_id"), table_name="usage_entries")
    op.drop_index(op.f("ix_usage_entries_created_at"), table_name="usage_entries")
    op.drop_table("usage_entries")
    op.drop_index(op.f("ix_memory_items_workspace_id"), table_name="memory_items")
    op.drop_index(op.f("ix_memory_items_user_id"), table_name="memory_items")
    op.drop_index(op.f("ix_memory_items_job_id"), table_name="memory_items")
    op.drop_table("memory_items")
    op.drop_index(op.f("ix_agent_graph_nodes_job_id"), table_name="agent_graph_nodes")
    op.drop_table("agent_graph_nodes")
    op.drop_table("user_plans")
    op.drop_table("plan_policies")
    op.drop_table("feature_flags")
    op.drop_table("admin_identities")
    op.drop_index(op.f("ix_admin_audit_subject"), table_name="admin_audit")
    op.drop_index(op.f("ix_admin_audit_created_at"), table_name="admin_audit")
    op.drop_index(op.f("ix_admin_audit_action"), table_name="admin_audit")
    op.drop_table("admin_audit")
    # ### end Alembic commands ###
