"""durable external write idempotency intents"""

import sqlalchemy as sa

from alembic import op

revision = "a4bcb8ee6bcb"
down_revision = "8c248b07f28e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "external_actions",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("result_encrypted", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["job_id"], ["agent_jobs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_index(
        op.f("ix_external_actions_job_id"), "external_actions", ["job_id"], unique=False
    )
    op.create_index(
        op.f("ix_external_actions_user_id"), "external_actions", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_external_actions_user_id"), table_name="external_actions")
    op.drop_index(op.f("ix_external_actions_job_id"), table_name="external_actions")
    op.drop_table("external_actions")
    # ### end Alembic commands ###
